### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by assemmarwan** [xuhong/ng2-timeago#6]
There is a problem when I use the module in Ionic 2. I do `npm install` and then add it to the imports, but the error shown below appears.

![screen shot 2017-04-23 at 5 41 52 pm](https://cloud.githubusercontent.com/assets/5578999/25314011/30835030-284c-11e7-81a5-9c00941b11a2.png)

**Comment by steeverdieu** [comment]
I got the same problem

**Comment by jzahka** [comment]
You could try `import {TimeAgo} from 'ng2-timeago';`
